### ISSUE TITLE
Ram usage

### ISSUE THREAD

**Issue by amorenew** [wandi34/springboot-helloworld-native#1]
> RAM Usage: ca 104.1 MB

Hello
I wonder why ram usage is not 30MB like the following blog?
https://blog.codecentric.de/en/2020/05/spring-boot-graalvm/

**Comment by wandi34** [comment]
Hey. Thanks for creating the issue. I have analyzed the RAM usage. During runtime it really just needs about 37 MB. I will correct that in the benchmark.
